// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoqggxfyzmrnodkrkaps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcWdneGZ5em1ybm9ka3JrYXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzI2MTIsImV4cCI6MjA3MzYwODYxMn0.uq8R7oEyJYTufSZeS5jp_Bz5qihP8ByIdL02epzrIkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});